export const FETCH_WALLET_REQUEST = 'FETCH_WALLET_REQUEST' as const;
export const FETCH_WALLET_SUCCESS = 'FETCH_WALLET_SUCCESS' as const;
export const FETCH_WALLET_ERROR   = 'FETCH_WALLET_ERROR'   as const;

export const TOPUP_WALLET_REQUEST = 'TOPUP_WALLET_REQUEST' as const;
export const TOPUP_WALLET_SUCCESS = 'TOPUP_WALLET_SUCCESS' as const;
export const TOPUP_WALLET_ERROR   = 'TOPUP_WALLET_ERROR'   as const;
