export const FETCH_INVENTORY_REQUEST = 'FETCH_INVENTORY_REQUEST' as const;
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS' as const;
export const FETCH_INVENTORY_ERROR   = 'FETCH_INVENTORY_ERROR'   as const;
